export const seoKeywords: string[] = [
    "Dutch Frontend Developer",
    "UI/UX Design",
    "Frontend Web Development",
    "Responsive Web Design",
    "User Interface (UI) Design",
    "User Experience (UX) Design",
    "Design Degree Holder",
    "Open-Source Development",
    "Open-Source Projects",
    "Magento 2 Development",
    "Magento 2 Expert",
    "SaaS Services",
    "SaaS Development",
    "Frontend Optimization",
    "Web Accessibility",
    "Performance Optimization",
    "HTML5",
    "CSS3",
    "JavaScript",
    "Progressive Web Apps (PWAs)",
    "Mobile-First Design",
    "Usability Testing",
    "Conversion Rate Optimization (CRO)",
    "A/B Testing",
    "E-Commerce Design",
    "Custom Magento Themes",
    "Dutch Web Development",
    "Responsive Design Principles",
    "Web Standards",
    "Frontend Frameworks (React, Vue, Angular)",
  ];
  